config/routes.rb
require 'sidekiq/web'
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  ActiveAdmin.routes(self)

  get "/chat" => "socket#chat", as: "chat"

  mount Facebook::Messenger::Server, at: 'bot'

  get '/welcome' => 'welcome#index', as: :welcome
  get '/policy' => 'welcome#policy', as: :policy
  get '/profile_picture/:id' => 'welcome#profile_picture', as: :profile_picture

  root 'welcome#entry'
  post :mail , controller: :welcome

  namespace :api do
      resources :log, only: [:create]
    resource :token, only: [] do
      post :gcm
      post :apns
      post :facebook
    end
  end

  namespace :users do
    resources :logins, only: [:new]
  end

  scope "/lviv" do
    get :events, controller: :welcome
  end

  resources :car_routes, only: [ :index, :show, :update, :destroy ]
  resources :routes
  resources :messages, only: [ :show, :create ]

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resource :download, only: [:show] do
    get :android, to: redirect('https://play.google.com/store/apps/details?id=io.drider.car&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1')
    get :ios, to: redirect('https://itunes.apple.com/ua/app/drider/id1101420670?ls=1&mt=8')
  end

  resource :account do
    get '/driver_role/:value', action: :driver_role, as: :driver_role
    get :route_required
    get :device_warning
    get :role_select
    resource :phone
  end

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from, class_name: 'User'
  belongs_to :to, class_name: 'User'
  belongs_to :car_request

  enum delivery_satatus: {
      posted:      'posted',
      delivered: 'delivered',
      read:      'read',
    }

  after_save do
    ActiveSupport::Notifications.instrument('message_saved', message: self)
  end

  scope :unread, -> (user) {
    where(delivery_status: ['posted','delivered'], to: user)
  }
  scope :index, -> (user) {
    sql =<<SQL
SELECT MAX(id) as id FROM messages JOIN
  (
    SELECT DISTINCT from_id AS cor_id WHERE to_id = ?
    UNION ( SELECT DISTINCT to_id AS cor_id FROM messages WHERE from_id = ? )
  ) cors
ON
    from_id = ? AND to_id = cors.cor_id
  OR
    to_id = ? AND from_id = cors.cor_id
GROUP BY cors.cor_id
SQL
    Message.where("id IN (#{sanitize_sql_array([sql, user.id,user.id,user.id,user.id])})").order('id DESC')
}
  scope :conversation, -> (user1, user2) {
    m = Message.arel_table
    Message.where(m[:to_id].eq(user1.id).and(m[:from_id].eq(user2.id)).or(m[:from_id].eq(user1.id).and(m[:to_id].eq(user2.id))))
  }


def cor(user)
  if user.id == to_id
    from
  else
    to
  end
end


def self.index1(user)
    sql =<<SQL
SELECT * from messages WHERE id in (
  SELECT MAX(id) as id FROM messages JOIN
    (
      SELECT DISTINCT from_id AS cor_id WHERE to_id = $1
      UNION ( SELECT DISTINCT to_id AS cor_id FROM messages WHERE from_id = $1 )
    ) cors
  ON
      from_id = $1 AND to_id = cors.cor_id
    OR
      to_id = $1 AND from_id = cors.cor_id
  GROUP BY cors.cor_id
)
SQL
Message.connection.exec_query(sql,'SQL', [[nil, user.id]])
end

#     lk=  <<SQL
#     id,
#     CASE
#      WHEN to_id = ? THEN from_id
#      WHEN from_id = ? THEN to_id
#     END as correspondent_id
#     SQL
#     conversations = Message.select(sanitize_sql_array((
#  , user.id))
#
# )

  #   correspondents = Message
  #                        .select('DISTINCT from_id AS cor_id')
  #                        .where(to: user)
  #                         .union(
  #                             Message
  #                                 .select('DISTINCT to_id AS cor_id')
  #                                 .where(from: user)
  #                         )
  #   cors = Message.arel_table.create_table_alias(correspondents, :cors)
  #
  #   msgs = Message.arel_table
  #   sql = msgs.project(msgs[:id].maximum, cors[:cor_id]).group(cors[:cor_id]).join(cors)
  #              .on((msgs[:to_id].eq(user.id).and(msgs[:from_id].eq(cors[:cor_id])))
  #                      .or(msgs[:from_id].eq(user.id).and(msgs[:to_id].eq(cors[:cor_id])))
  #              )
  #              .to_sql
  #   printf sql
  #   # ActiveRecord::Base.connection.execute(sql)
  #
  # }
  #
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  layout 'amp'
  # before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :user_required
  before_action { menu_set_active('messages') }
  # after_action :mark_messages_as_read, only: [:show]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.index(current_user)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    @correspondent = User.find(params[:id])
    @structed_messages = structed_messages
    respond_to do |format|
      format.html {
        mark_messages_as_read
        @template = render_to_string partial: 'messages.html.mustache'
      }
      format.json do
        result= {}
        if params[:cmt_id].to_i == @correspondent.id
          mark_messages_as_read
          result[:messages_html] = render_to_string(partial: 'messages', formats: :html)
        end
        result[:urc] = unread_requests_count
        result[:umc] = unread_messages_count
        result[:ut] = result[:urc] + result[:umc]
        render json: result
      end
    end
  end

  # POST /messages
  # POST /messages.json
  def create
    @correspondent = User.find(params[:to_id])
    if params[:body].present?
      msg = Message.create!(from: current_user, to: @correspondent, body: params[:body])
      MessageNotifier.new(@correspondent).perform
    end
    render json: { messages: structed_messages }
  end


  def mark_messages_as_read
    to_update = @messages.to_a.select{|m| m.delivery_status != 'read' && m.to_id == current_user.id}
    Message.where(id: to_update).update_all(delivery_status: 'read') if to_update.present?
  end

  private

  def messages_for_correspondent
    Message.conversation(@correspondent, current_user).order('id DESC').limit(30).reverse
  end


  def structed_messages
    messages = Message.conversation(@correspondent, current_user).order('id DESC').limit(30).reverse
    grouped = messages.group_by {|m| m.created_at.to_date}
    grouped.keys.sort.reverse.each_with_index.map do |date, i|
      messages = grouped[date].sort_by(&:created_at).reverse.map {|m|
        r = {
          body: m.body,
          created_at: m.created_at.to_formatted_s(:time)
        }
        r[:className] = ' mymessage' if m.from_id == current_user.id
        r
      }
      if i>0
        {
          date: date,
          messages: messages
        }
      else
        {
          messages: messages
        }
      end
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    # def set_message
    #   @message = Message.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def message_params
    #   params.require(:message).permit(:from, :to, :car_request, :body, :seen_at)
    # end
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from %><br>
    <%= f.number_field :from %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.number_field :to %>
  </div>
  <div class="field">
    <%= f.label :car_request %><br>
    <%= f.number_field :car_request %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :seen_at %><br>
    <%= f.datetime_select :seen_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/_message.html.slim
-cor = message.cor(current_user)
li
  div.ava-line
    =link_to message_path(cor) do
      =image_tag cor.image_url, class: 'avatar'
      =cor.name
    '
    span.text-muted =tiny_time_from_now(message.created_at)
    div
      =message.body

app/views/messages/_messages.html.slim
-@messages_by_date.each do |date, messages|
  li
    div style="clear: both; text-align: center"
      =date
  -messages.each do |message|
    -if message.car_request && message.car_request.updated_at <= message.created_at
      li style="clear: both"
        =render partial: 'car_requests/car_request', locals: { car_request: message.car_request }
    li
      -if message.from_id == current_user.id
        div.alert.alert-info.pull-right style="text-align: right; width: 80%"
          =message.body
          '
          span.text-muted =message.created_at.to_formatted_s(:time)
      -else
        div.alert.alert-warning.pull-left style="text-align: left; width: 80%"
          =message.body
          span.pull-right.text-muted =message.created_at.to_formatted_s(:time)

app/views/messages/index.html.slim
h3 Повідомлення
ul.list-unstyled
  =render @messages

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<% content_for :title, "Повідомлення від #{@correspondent.name}" %>

<main class="content" role="main">
  <header class="blog-header">
    <h2><%= @correspondent.name %></h2>
    <amp-img src="<%= @correspondent.image_url %>" width="50" height="50"/>
  </header>
  <div class="cf frame">
    <div class="messages">
      <form method="POST" action-xhr="<%= messages_path %>" target="_top">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <%= hidden_field_tag :to_id, @correspondent.id %>
        <%= text_field_tag :body, '', class: 'hide-on-success', placeholder: 'Повідомлення', autofocus:1, tabindex:1 %>
        <%= button_tag 'Надіслати', class: 'btn hide-on-success' %>
        <div submit-error>
        </div>
        <div submit-success>
          <template type="amp-mustache">
            <%= @template.html_safe %>
          </template>
        </div>
        <div class="hide-on-success">
          <%= Mustache.render(@template, messages: @structed_messages).html_safe %>
        </div>
      </form>
    </div>
  </div>
</main>

app/views/messages/show.html.slim
div.messages
  =image_tag @correspondent.image_url
  =@correspondent.name
  ul.list-unstyled.messages-list
    =render partial: 'messages'
  br style="clear: both;"
  div style="height:60px"
  div style="position: fixed; bottom: 0px"
    =form_tag messages_path do
      =hidden_field_tag :to_id, @correspondent.id
      div.input-group
        =text_field_tag :body,'', class: 'form-control', placeholder: 'Повідомлення'
        span.input-group-btn
          =button_tag 'Надіслати', class: 'btn btn-default btn-primary'