config/routes.rb
require 'sidekiq/web'
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  ActiveAdmin.routes(self)

  get "/chat" => "socket#chat", as: "chat"

  mount Facebook::Messenger::Server, at: 'bot'

  get '/welcome' => 'welcome#index', as: :welcome
  get '/policy' => 'welcome#policy', as: :policy
  get '/profile_picture/:id' => 'welcome#profile_picture', as: :profile_picture

  root 'welcome#entry'
  post :mail , controller: :welcome

  namespace :api do
      resources :log, only: [:create]
    resource :token, only: [] do
      post :gcm
      post :apns
      post :facebook
    end
  end

  namespace :users do
    resources :logins, only: [:new]
  end

  scope "/lviv" do
    get :events, controller: :welcome
  end

  resources :car_routes, only: [ :index, :show, :update, :destroy ]
  resources :routes
  resources :messages, only: [ :show, :create ]

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resource :download, only: [:show] do
    get :android, to: redirect('https://play.google.com/store/apps/details?id=io.drider.car&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1')
    get :ios, to: redirect('https://itunes.apple.com/ua/app/drider/id1101420670?ls=1&mt=8')
  end

  resource :account do
    get '/driver_role/:value', action: :driver_role, as: :driver_role
    get :route_required
    get :device_warning
    get :role_select
    resource :phone
  end

end

app/views/shared/_gmap.html.erb
<script type="text/javascript">
//  (function() {
    <% if @map_data_url %>
      var data_url = '<%= @map_data_url %>';
    <% end %>

    <% if @from_marker %>
      var from_marker = <%= "new google.maps.LatLng(#{@from_marker.y}, #{@from_marker.x})".html_safe %>;
    <% end %>

    <% if @to_marker %>
      var to_marker = <%= "new google.maps.LatLng(#{@to_marker.y}, #{@to_marker.x})".html_safe %>;
    <% end %>

    var startMarker = new google.maps.Marker({
      draggable: true,
      title: 'Початок'
    });
    var finishMarker = new google.maps.Marker({
      draggable: true,
      title: 'Призначення',
      icon: '<%= image_path("icons/finish.png") %>'
    });
    var from = $('#car_search_from');
    var to = $('#car_search_to');
    var map;
    function initialize() {
      var mapOptions = {
        center: {lat: 49.8419071, lng: 24.0315675},
        zoom: 12
      };
      geocoder = new google.maps.Geocoder();
      map = new google.maps.Map(document.getElementById('map-canvas'),
          mapOptions);
      startMarker.setMap(map);
      finishMarker.setMap(map);

      var onDrag = function(e){
        setMarker(this, e.latLng);
      };
      google.maps.event.addListener(startMarker, 'dragend', onDrag);
      google.maps.event.addListener(finishMarker, 'dragend', onDrag);
      google.maps.event.addListener(map, 'click', function (e) {
        if (!empty(from) && !empty(to)){
          setMarker(startMarker, null);
          setMarker(finishMarker, null);
        }

        if (empty(from)) setMarker(startMarker, e.latLng); else setMarker(finishMarker, e.latLng);

//        placeMarker(e.latLng, map);
//          console.log(a);
//            map.setCenter();
      });
      map.data.setStyle(function(feature) {
          var color = feature.getProperty('color');
        console.log(color);
          return {
            strokeColor: color
          };
      });
      map.data.addListener('mouseover', function (event) {
        map.data.revertStyle();
        map.data.overrideStyle(event.feature, {strokeWeight: 5});
      });

      map.data.addListener('mouseout', function (event) {
        map.data.revertStyle();
      });
      map.data.addListener('click', function (event) {
        var id = event.feature.getProperty('id');
        location.hash = "#route" + id;
      });



      if ('undefined' != typeof from_marker) startMarker.setPosition(from_marker);
      if ('undefined' != typeof to_marker) finishMarker.setPosition(to_marker);
      if ('undefined' != typeof data_url) map.data.loadGeoJson(data_url);
    }

    function placeMarker(position, map) {

      var marker = new google.maps.Marker({
        position: position,
        map: map
      });
//      map.panTo(position);
      if ( !startMarker || (startMarker && finishMarker) ) setStartMarker(marker)
      if ( !finishMarker ) setFinishMarker(marker);
    }

    function getOrCreateMarker(latLng){
//      if (startMarker && en)
    }

    function setMarker(marker, value){
      var ref;
      if (marker == startMarker) ref = from; else ref = to;
      if (value){
        ref.val(value.lat()+", "+value.lng() || '');
        marker.setPosition(value);
        marker.setMap(map);
        geocoder.geocode({'latLng': value}, function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            if (results[1]) {
              console.log(results[1]);
            }
          }
        });

      } else {
        ref.val("");
        marker.setMap(null);
      }
    }


    function empty(ref){
      return 0 == ref.val().length;
    }

    google.maps.event.addDomListener(window, 'load', initialize);
//  })();
</script>

<div id="map-canvas"></div>

app/views/shared/_navbar.html.slim
-driver_role = current_user && current_user.driver_role
nav id="tf-menu" class="navbar navbar-default on navbar-fixed-top"
  div class="container"
    div class="navbar-header"
      a class="navbar-brand hidden-xs hidden-sm" href="/" Drider
      button type="button" class="navbar-toggle collapsed pull-right" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span class="sr-only">Toggle navigation
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"

    div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"
      ul class="nav navbar-nav navbar-left"
        -if current_user.try(:role_defined?)
          -if driver_role && current_user.ever_drive
            li class=('active' if 'routes' == @active_menu)
              a href="#{car_routes_path}" Маршрути
      -if current_user
        ul class="nav navbar-nav navbar-right"
          li
            a class="navbar-brand" href="/"
              img alt="Brand" src="#{current_user.image_url}"