config/routes.rb
require 'sidekiq/web'
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  ActiveAdmin.routes(self)

  get "/chat" => "socket#chat", as: "chat"

  mount Facebook::Messenger::Server, at: 'bot'

  get '/welcome' => 'welcome#index', as: :welcome
  get '/policy' => 'welcome#policy', as: :policy
  get '/profile_picture/:id' => 'welcome#profile_picture', as: :profile_picture

  root 'welcome#entry'
  post :mail , controller: :welcome

  namespace :api do
      resources :log, only: [:create]
    resource :token, only: [] do
      post :gcm
      post :apns
      post :facebook
    end
  end

  namespace :users do
    resources :logins, only: [:new]
  end

  scope "/lviv" do
    get :events, controller: :welcome
  end

  resources :car_routes, only: [ :index, :show, :update, :destroy ]
  resources :routes
  resources :messages, only: [ :show, :create ]

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resource :download, only: [:show] do
    get :android, to: redirect('https://play.google.com/store/apps/details?id=io.drider.car&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1')
    get :ios, to: redirect('https://itunes.apple.com/ua/app/drider/id1101420670?ls=1&mt=8')
  end

  resource :account do
    get '/driver_role/:value', action: :driver_role, as: :driver_role
    get :route_required
    get :device_warning
    get :role_select
    resource :phone
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    p current_user
  end

  def entry
    redirect_to welcome_url
  end

  def mail
    ActionMailer::Base.mail(
            from: '700@2rba.com',
            to: 'reports@mx.2rba.com',
             body: params[:email]+ ' ' + params[:body],
             content_type: "text/plain",
             subject: 'Drider mail form'
    ).deliver
    redirect_to :welcome, notice: "Дякуємо за звернення"
  end

  def events
    render :json => RecentEventsSerializer.new(RecentEventsService.new)
  end

  def policy

  end

  def profile_picture
    user = User.find params[:id]
    proxy_remote(user.image_url)
  end

  private

  def warning_required?
    'ios' == params[:client] &&
        (params[:location] != 'Authorized' || params[:notifications] == '')
  end

  def proxy_remote(url)
    headers['X-Accel-Redirect'] = "/proxy_remote/#{url.sub(/^https?\:\/\//, '')}"
    render :nothing => true
  end
end

app/views/welcome/index.html.erb
<% @layout_name = 'landing' %>

<div class="landing">
  <!-- Navigation
    ==========================================-->
    <nav id="tf-menu" class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Drider</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#tf-home" class="page-scroll">Наверх</a></li>
            <li><a href="#tf-about" class="page-scroll">Чому</a></li>
            <li><a href="#tf-team" class="page-scroll">Як</a></li>
            <li><a href="#tf-services" class="page-scroll">Водію</a></li>
            <li><a href="#tf-clients" class="page-scroll">Пасажиру</a></li>
            <li><a href="#city-map" class="page-scroll">Мара</a></li>
            <li><a href="#tf-testimonials" class="page-scroll">Контакт</a></li>
            <% if current_user %>
              <a class="navbar-brand" href="/">
                <img alt="Avatar" src="<%= current_user.image_url %>" />
              </a>
            <% else %>
            <li><a href="<%= new_user_session_path %>" class="page-scroll">Вхід</a></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Home Page
    ==========================================-->
    <div id="tf-home" class="text-center">
        <div class="overlay">
            <div class="content">
                <h1><strong><span class="color">Drider</span></strong> вітає вас</h1>
                <p class="lead">Сервіс спільних поіздок</p>
              <div class="container" style="max-width: 400px;">

                <div style="margin-top: 24px;">
                  <div class="fb-messengermessageus"
                    messenger_app_id="1589454371319440"
                    page_id="1026215597422812"
                    color="blue"
                    size="xlarge" >
                  </div>
                </div>
              </div>
                <a href="#tf-about" class="fa fa-angle-down page-scroll"></a>
            </div>
        </div>
    </div>

    <!-- About Us Page
    ==========================================-->
    <div id="tf-about">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img src="<%= image_path('landing/car.jpg') %>" class="img-responsive">
                </div>
                <div class="col-md-6">
                    <div class="about-text">
                        <div class="section-title">
                            <h4></h4>
                            <h2><strong>Підвезти</strong> та бути <strong>підвезеним</strong></h2>
                            <hr>
                            <div class="clearfix"></div>
                        </div>
                        <p class="intro">
                          Водіям: Тут мені запропонують підвести цікавих пасажирів
                        </p>
                        <p class="intro">
                          Пасажирам: Тут ви знайдете водія, що вас підвезе
                        </p>
                        <ul class="about-list">
                            <li>
                                <span class="fa fa-dot-circle-o"></span>
                                <strong></strong> <em>їдучи разом ми робимо дороги вільнішими</em>
                            </li>
                            <li>
                                <span class="fa fa-dot-circle-o"></span>
                                <strong></strong> <em>нам цікаво спілкуватися в дорозі</em>
                            </li>
                            <li>
                                <span class="fa fa-dot-circle-o"></span>
                                <strong></strong> <em>ми розділяємо витрати на дорогу</em>
                            </li>
                        </ul>
                      <h5>Приєднатись вже за допомогою <%= link_to 'Messenger', 'https://m.me/1026215597422812'%></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Team Page
    ==========================================-->
    <div id="tf-team" class="text-center">
        <div class="overlay">
            <div class="container">
                <div class="section-title center">
                    <h2><strong>Як це працює</strong></h2>
                    <div class="line">
                        <hr>
                    </div>
                </div>
              <div>
                <ul class="about-list ">
                  <li>
                    <span class="fa fa-dot-circle-o"></span> Пасажир вказує маршрут поїздки
                  </li>
                  <li>
                    <span class="fa fa-dot-circle-o"></span> Водії з відповідними маршрутами отримують запити на згоду підвезти
                  </li>
                  <li>
                    <span class="fa fa-dot-circle-o"></span> Після згоди водія, пасажир отримує можливість подзвонити водію і домовитись як зустрітись
                  </li>
                </ul>
              </div>
              <h5>Приєднатись вже за допомогою <%= link_to 'Messenger', 'https://m.me/1026215597422812'%></h5>

            </div>
        </div>
    </div>


  <!-- About Us Page
  ==========================================-->
  <div id="tf-services">
      <div class="container">
          <div class="row">
              <div class="col-md-6">
                  <img src="<%= image_url('landing/driver.jpg') %>" class="img-responsive">
              </div>
              <div class="col-md-6">
                  <div class="about-text">
                      <div class="section-title">
                          <h2>Водію</h2>
                          <hr>
                          <div class="clearfix"></div>
                      </div>
                      <ul class="about-list">
                          <li>
                              <span class="fa fa-dot-circle-o"></span>
                              <strong></strong> <em>Почати спілкування з <%= link_to 'ботом', 'https://m.me/1026215597422812'%>, і отримати посилання на мобільний застосунок</em>
                          </li>
                          <li>
                              <span class="fa fa-dot-circle-o"></span>
                              <strong></strong> <em>За допомогою мобільного застосунка записати маршрути
                            </em>
                          </li>
                          <li>
                              <span class="fa fa-dot-circle-o"></span>
                              <strong></strong> <em>Вибирати цікавих попутчиків серед запитів і мати гарну подорож</em>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </div>


    <!-- Clients Section
    ==========================================-->
    <div id="tf-clients" class="text-center">
        <div class="overlay">
            <div class="container">

                <div class="section-title center">
                    <h2><strong>Пасажиру</strong></h2>
                    <div class="line">
                        <hr>
                    </div>
                </div>
              <div class="row">
                  <div class="col-md-6">
                      <img src="<%= image_path('landing/passenger.jpg') %>" class="img-responsive">
                  </div>
                  <div class="col-md-6">
                      <div class="about-text">
                          <ul class="about-list">
                              <li>
                                  <span class="fa fa-dot-circle-o"></span>
                                  <strong></strong> <em>Почати спілкування з <%= link_to 'ботом', 'https://m.me/1026215597422812'%></em>
                              </li>
                              <li>
                                  <span class="fa fa-dot-circle-o"></span>
                                  <strong></strong> <em>Вказати звідки і куди потрібно заіхати</em>
                              </li>
                              <li>
                                  <span class="fa fa-dot-circle-o"></span>
                                  <strong></strong> <em>Отримати підтвердження, зателефонувати водію і домовитись як зустрітись</em>
                              </li>
                          </ul>
                      </div>
                  </div>
              </div>

            </div>
        </div>
    </div>

    <!-- Portfolio Section
    ==========================================-->
    <div id="city-map">
        <div class="container"> <!-- Container -->
            <div class="section-title text-center center">
                <h2><strong>Мапа</strong></h2>
                <div class="line">
                    <hr>
                </div>
                <div class="clearfix"></div>
                <small><em></em></small>
            </div>


          <div id="map-canvas"></div>
            <div class="space"></div>
          <% active_stats = CarRoute.active_stats %>
          <h3 style="
              text-align: left;
              /* margin-left: 68px; */
          ">Активних маршрутів <span class="label label-default"> <%= active_stats['routes_count'] %></span></h3>
          <h3 style="
                        text-align: left;
          ">Водіїв <span class="label label-default"> <%= active_stats['users_count'] %></span></h3>
        </div>
    </div>

    <!-- Testimonials Section
    ==========================================-->
    <div id="tf-testimonials" class="text-center">
        <div class="overlay">
            <div class="container">
              <div class="row">
                  <div class="col-md-8 col-md-offset-2">

                      <div class="section-title center">
                          <h2><strong>Звертайтесь</strong> по всім питанням</h2>
                          <div class="line">
                              <hr>
                          </div>
                          <div class="clearfix"></div>
                          <small><em></em></small>
                      </div>

                      <%= form_tag mail_path do %>
                          <div class="row">
                              <div class="col-md-6">
                                  <div class="form-group">
                                      <label for="exampleInputEmail1">Email адреса</label>
                                      <input name="email" type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
                                  </div>
                              </div>
                              <div class="col-md-6">
                              </div>
                          </div>
                          <div class="form-group">
                              <label for="exampleInputEmail1">Повідомлення</label>
                              <textarea class="form-control" rows="3" name="body"></textarea>
                          </div>

                          <button type="submit" class="btn tf-btn btn-default">Надіслати</button>
                      <% end %>
                    <a target="_blank" class="btn btn-success" href="https://github.com/drider-io/drider/issues">Пропозиції</a>

                  </div>
              </div>

            </div>
        </div>
    </div>


    <nav id="footer">
        <div class="container">
            <div class="pull-left fnav">
                <p></p>
            </div>
            <div class="pull-right fnav">
                <ul class="footer-social">
                    <li><a href="https://www.facebook.com/drider.io"><i class="fa fa-facebook"></i></a></li>
                    <!--<li><a href="#"><i class="fa fa-dribbble"></i></a></li>-->
                    <!--<li><a href="#"><i class="fa fa-google-plus"></i></a></li>-->
                    <!--<li><a href="#"><i class="fa fa-twitter"></i></a></li>-->
                </ul>
            </div>
        </div>
    </nav>
</div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
    <!--<script type="text/javascript" src="js/jquery.1.11.1.js"></script>-->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!--<script type="text/javascript" src="js/bootstrap.js"></script>-->
    <!--<script type="text/javascript" src="js/SmoothScroll.js"></script>-->
    <!--<script type="text/javascript" src="js/jquery.isotope.js"></script>-->

    <!--<script src="js/owl.carousel.js"></script>-->

    <!-- Javascripts
    ================================================== -->
    <!--<script type="text/javascript" src="js/main.js"></script>-->

app/views/welcome/policy.html.erb
<div style="margin: 0 20px">
<h2 id="1">
  Політика конфіденційності
</h2>

<h3>
  Ми збираємо особисту інформацію і активність користувача
</h3>
<p>
  Ми використовуємо ідентифікатори унікальності для ідентифікації комп'ютера або пристрою, таким чином, ми можемо поставити кращий досвід користування. Наші системи також зареєструвати таку інформацію, як ідентифікатор пристрою, операційної системи і IP-адреса. 
  Ми також збирати інформацію: наприклад, пристрій локалізації, версія програми, дозволи надані додатку. Ми можемо також отримати доступ профілю та іншої інформації від послуг, таких як Facebook. Наші системи можуть зв'язати цю особисту інформацію з вашої діяльності в ході надання послуг для Вас. Ми свідомо не контактуємо або збираємо особисту інформацію від дітей молодше 13 років Якщо ви вважаєте, що ми необережно зібрали таку інформацію, будь ласка, зв'яжіться з нами, щоб ми могли оперативно отримати згоду батьків або видалити інформацію.
</p>

<h3>Ми збираємо і зберігаємо ваші пошуки маршрутів.</h3>
<p>
  Пошуки які ви зробили зберігаються, доступні для переглюду іншими і можуть використовуватись в подальшому аби знайти маршрут водія який зможе вас підвезти як вказано в пошуку. Ми можемо повідмляти вас і потенційного водія про відповідні пошуки. Ви можетк переглюнути пошуки в меню “Пошук водія”
</p>

<h3>Ми збираємо і зберігаємо ваше точне місце розташування</h3>
<p>Ваше точне розташування збирається і передається нам під час використання додатку і підключенного живлення. Це необхідно аби записати маршрут водія.
Ці маршрути ви можете побачити в меню “Маршрути”. Ваші маршрути або їх частина може бути доступна для перегляду всім бажаючим. Це зроблено аби ви могли знайти пасажира для сумісних поїздок.
</p>

<h3>Ми збираємо і зберігаємо ваші публічні дані профілю Facebook
</h3>
<p>
  З вашої згоди ми збираємо і зберігаємо дані вашого публічного профілю Facebook. Такі як: ім’я, призвище, стать, приблизний вік, аватар. Ми показуємо відвідувачам ваше ім’я, призвище, аватар. Це зроблено аби користувачі сервісу ідентифікували один одного. Ми можемо передавати ваше повне ім’я і аватар партнерам.
</p>

<h3>Ми збираємо і зберігаємо ваш email</h3>
<p>З вашої згоди ми збираємо і зберігаємо ваш email. Ваш email не розповсюджуєтся і не передається іншим сторонам. Ми можемо надсилати вам листи аби повідомити про події які стосуються особисто вас, новини, рекламу. Ви можете в будь-який момент відмовитись від листів скориставшись відповідним посиланням в листі.
</p>

<h3>Ми розсилаємо push notifications
</h3>
<p>Ми розсилаємо push notifications у випадку події яка вимагає вашої уваги. Наприклад: повідомлення від іншого користувача, зміна статусу запита, та інше.
</p>

<h3>Ви можете залишити заявку, щоб побачити свої персональні дані.
</h3>
<p>Ви можете зв'язатися з нами по електронній пошті, щоб запросити, щоб побачити цю інформацію.
</p>

<h3>Ми можемо зберегти дані на невизначений термін.
</h3>
<p>Ми можемо зберегти дані на невизначений термін.
</p>

<h3>Ми можемо ділитися особистими даними з компаніями, яким ми довіряємо.
</h3>
<p>Ми можемо ділитися анонімною інформацією з довіреними партнерами, з тим, щоб надати вам відповідні реклами, пропозицій або послуги.
</p>

<h3>Ви можете задати питання приватності.
</h3>
<p>
  Якщо у вас є які-небудь питання або сумніви з приводу нашої політики конфіденційності, будь ласка, зв'яжіться з нами: info@drider.io
</p>

<h3>Постачальники послуг доступу до даних від нашого імені.
</h3>
<p>Для того, щоб служити вам, ми можемо передавати вашу особисту і анонімну інформацію з іншими компаніями, в тому числі постачальників і підрядників. Їх використання інформації обмежується цих цілей, а також з урахуванням угод, які вимагають від них, щоб зберегти інформацію в таємниці. Наші постачальники надають впевненість в тому, що вони вживають заходів для забезпечення збереження даних, які вони тримають від нашого імені, хоча безпеку даних не може бути гарантована. Аналітика компанії можуть отримати доступ до анонімні дані (наприклад, ваш IP-адреса або ідентифікатор пристрою), щоб допомогти нам зрозуміти, як використовуються наші послуги. Вони використовують ці дані виключно від нашого імені. Вони не поділяють його інакше як в агрегированной формі; ніякі дані не поділяють, як для будь-якого окремого користувача. 
</p>

<h3>Ми вживаємо заходів для захисту особистої інформації
</h3>
<p>Ми приймаємо розумні заходи, щоб убезпечити вашу особисту інформацію від несанкціонованого доступу або розголошення. Проте, жоден з методів безпеки або шифрування не може бути гарантована для захисту інформації від хакерів або людської помилки.
</p>

<h3>Особливі ситуації можуть зажадати розкриття ваших даних.
</h3>
<p>
  Для управління послугою, ми також можемо зробити ідентифікувати і анонімні дані третім особам в цих обмежених обставин: (1) з Вашої згоди, (2), коли ми маємо сумлінне припущення, що потрібно за законом, (3), коли у нас є сумлінне припущення, що це необхідно для захисту наших прав або власності, або (4) до будь-якого наступника або покупця у формі злиття, придбання, ліквідації, розпуску або продажу активів. Ваше згода не потрібна для розкриття в цих випадках, але ми спробуємо повідомити вас, наскільки це дозволено законом, щоб зробити це.
</p>

<h3>Ви можете отримати детальнішу інформацію про конфіденційність.
</h3>
<p>Ця політика конфіденційності була оновлена ​​29-квітня-2016. Наша політика конфіденційності може змінюватися час від часу. Якщо ми будемо вносити істотні зміни в нашій політиці, ми розмістимо помітне повідомлення на нашому веб-сайті або в додатку.
</p>
<%= link_to 'Прийняти', new_user_session_path, class: 'btn btn-primary' %>
<%= link_to 'Відмовитись', '#1', class: 'btn btn-link' %>
</div>