config/routes.rb
require 'sidekiq/web'
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  ActiveAdmin.routes(self)

  get "/chat" => "socket#chat", as: "chat"

  mount Facebook::Messenger::Server, at: 'bot'

  get '/welcome' => 'welcome#index', as: :welcome
  get '/policy' => 'welcome#policy', as: :policy
  get '/profile_picture/:id' => 'welcome#profile_picture', as: :profile_picture

  root 'welcome#entry'
  post :mail , controller: :welcome

  namespace :api do
      resources :log, only: [:create]
    resource :token, only: [] do
      post :gcm
      post :apns
      post :facebook
    end
  end

  namespace :users do
    resources :logins, only: [:new]
  end

  scope "/lviv" do
    get :events, controller: :welcome
  end

  resources :car_routes, only: [ :index, :show, :update, :destroy ]
  resources :routes
  resources :messages, only: [ :show, :create ]

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resource :download, only: [:show] do
    get :android, to: redirect('https://play.google.com/store/apps/details?id=io.drider.car&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1')
    get :ios, to: redirect('https://itunes.apple.com/ua/app/drider/id1101420670?ls=1&mt=8')
  end

  resource :account do
    get '/driver_role/:value', action: :driver_role, as: :driver_role
    get :route_required
    get :device_warning
    get :role_select
    resource :phone
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  layout 'account'
  before_action :user_required


  def show
    route_helper
  end


  def update

  end

  def route_required

  end

  def role_select

  end

  def device_warning
    @client = params[:client]
    @location = params[:location]
    @notifications = params[:notifications]
  end

  def driver_role
    current_user.update!(driver_role: params[:value])
    redirect_to :root
  end

  private
  def account_params
       params.permit(:driver_role)
  end

end

app/views/accounts/device_warning.html.slim
h1 Потрібно налаштувати мобільний/планшет
-if 'ios' == @client
  -if @location != 'Authorized'
    p
      h2 Служба локаціі
      em Служба локаціі потрібна аби записувати маршрут водія
      blockquote Увімкнути службу локаціі можна в Параметрах телефона/планшета
      |Параметри -> Приватність -> Служба локації -> Drider -> Під час роботи програми
  -if @notifications == ''
    p
      h2 Сповіщення
      em Сповіщення необхідні аби повідомити вас про повідомленяя від спільноти
      blockquote Увімкнути сповіщення можна в Параметрах телефона/планшета
      |Параметри -> Сповіщення -> Drider -> Дозволити сповіщення -> Включити

app/views/accounts/role_select.html.slim
h1 Хто ви ?

=link_to 'Я водій', driver_role_account_path(value: true), class: 'btn btn-block btn-primary btn-lg'

=link_to 'Я пасажир', driver_role_account_path(value: 'false'), class: 'btn btn-block btn-success btn-lg'

small Ви можете змінити це в будь-який момент

app/views/accounts/route_required.html.slim
div.driver-instruction
  h1 УВАГА
  div.alert.alert-danger
    'Аби бути водієм і підвозити інших будь-ласка ознайомтесь з інструкцією
  div.bigger
    -unless mobile_app?
      div.alert.alert-info
        ol
          li
            |Скачайте додаток для
            '
            =link_to 'iOS', ios_download_path
            | /
            =link_to 'Андроїд', android_download_path
          li Знов увійдіть через фейсбук в додатку
      br
    'Для запису маршрута необхідно:
    div.alert.alert-info
      ol
        li
          | В телефоні/планшеті потрібно мати:
          ul
            li мобільний інтернет
            li GPS
        li В авто: Зарядне до мобільного
    strong
      'Як сідаєте в авто, підключаєте живлення, запускаєте додаток, переконуєтесь що всі 3 індикатора зелені і їдете своїм щоденим маршрутом.
      'Маршрут запишеться і з’явится в системі через 15 хв після закінчення подорожі
br
-if mobile_app?
  h4 Чомуб не спробувати і не підключити мобільний до живлення прямо зараз ?
-else
  h4 Вдалого запуску